### ISSUE TITLE
gen.data='heterozygot' parameter

### ISSUE THREAD

**Issue by cks2903** [arthurkorte/MTMM#2]
I am using the gen.data='heterozygot' parameter when running MTMM, but this seems to generate wrong MAC values, as my data are coded as 0 (homozygous), 1 (heterozygote) and 2 (homozygote).
In the output it is clear that it considers 0 to code heterozygous loci, whereas 1 and 2 are both considered homozygous.

Does this affect the GWAS analysis as well?

**Comment by arthurkorte** [comment]
It should not affect the GWAS results, but I will look at the code and fix it for the MAC values as well 
Currently at a conference, but will try to do it over the weekend

**Comment by cks2903** [comment]
Thanks. Is there any updates on the issue, yet?

**Comment by arthurkorte** [comment]
During the update I also changed the Allele count. Should work fine now with heterozygous data as well.
